package cn.blaze.domain;

import java.util.Date;

public class FileResources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.publisher_id
     *
     * @mbg.generated
     */
    private String publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.publish_time
     *
     * @mbg.generated
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.group_type
     *
     * @mbg.generated
     */
    private String groupType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.isvalid
     *
     * @mbg.generated
     */
    private String isvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_resources.file_desc
     *
     * @mbg.generated
     */
    private String fileDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.id
     *
     * @return the value of file_resources.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.id
     *
     * @param id the value for file_resources.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.file_name
     *
     * @return the value of file_resources.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.file_name
     *
     * @param fileName the value for file_resources.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.publisher_id
     *
     * @return the value of file_resources.publisher_id
     *
     * @mbg.generated
     */
    public String getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.publisher_id
     *
     * @param publisherId the value for file_resources.publisher_id
     *
     * @mbg.generated
     */
    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId == null ? null : publisherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.publish_time
     *
     * @return the value of file_resources.publish_time
     *
     * @mbg.generated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.publish_time
     *
     * @param publishTime the value for file_resources.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.file_path
     *
     * @return the value of file_resources.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.file_path
     *
     * @param filePath the value for file_resources.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.group_id
     *
     * @return the value of file_resources.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.group_id
     *
     * @param groupId the value for file_resources.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.group_type
     *
     * @return the value of file_resources.group_type
     *
     * @mbg.generated
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.group_type
     *
     * @param groupType the value for file_resources.group_type
     *
     * @mbg.generated
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType == null ? null : groupType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.isvalid
     *
     * @return the value of file_resources.isvalid
     *
     * @mbg.generated
     */
    public String getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.isvalid
     *
     * @param isvalid the value for file_resources.isvalid
     *
     * @mbg.generated
     */
    public void setIsvalid(String isvalid) {
        this.isvalid = isvalid == null ? null : isvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_resources.file_desc
     *
     * @return the value of file_resources.file_desc
     *
     * @mbg.generated
     */
    public String getFileDesc() {
        return fileDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_resources.file_desc
     *
     * @param fileDesc the value for file_resources.file_desc
     *
     * @mbg.generated
     */
    public void setFileDesc(String fileDesc) {
        this.fileDesc = fileDesc == null ? null : fileDesc.trim();
    }
}